version: '3.8'

services:
  backend:
    build:
      context: ./baxi-api
    ports:
      - "${PORT:-4000}:4000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=${REDIS_URL}
      - SMS_KEY=${SMS_KEY}
      - OTP_RESEND_SECONDS=${OTP_RESEND_SECONDS}

  frontend:
    build:
      context: ./baxi-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - baxi-api
